language: php
php:
  - 7.2
services:
  - mysql
before_script:
#  - composer install
#script: ./vendor/bin/phpunit ./tests
script: echo 'none'
deploy:
  provider: heroku
  app: curso-github-cefire-salva
  on: master
  skip_cleanup: true
  api_key:
    secure: aJT3Ovqf3TeLgObK/avi2tRUmbmKdeCBtFJJt6CXEXdVNfkjNyFHzOiaCVqNUq4hu0GEA7YyffuQ0b/IipHqN1PXG0QoxXVPmJknfDS3XFb8JosrUbMWsRTPhbSC4Aoqu89h7zFMGCBGRQqwXD6jlbKl3mJNahPMZyiidPb809b+5SXWknvX3kHk+aM0lHOGfC4ahSx0BvQ/8+Oj+lGg5mn099THAJzwUe97RLP+UjwQFudxYZFkA27iClnSyrWOm29d3BhDxxEuS7TXbB9Bgw617uQUxJ+LWfLKpyoKP7jFe5u4kB07iU1SH+91ZHmvM9R2HbwD05p64fzPMcUjTv2Mo/0t9aHnRTE7CUZTuzCRmoO5vwgQ+8vVvNQpoPqXFs4u2lib6iN1KjtmeGLBXm6b4b4vEUYEMftE+2+bO2gnoJP8Zr11STtF6OQ+VALZi9fJt4jPaf27zYybdIr3byIC+ag/vitzmj9i/IVO62DcqqsC1+PELY/8umNCuhks1Ozrqeu6MM/n0jVSxFPP0pL7osOIXHLXnpJSkhhMO1u4auK8hcwiT3waDuRYjcxSs1ipIvPOryNO5oK8U9/dHFF1hSmfzFGobSkdPod20iyQeAre16m3Qln2eUgHfHb8wG1p2BfqANbbSLGcx5PRXEMzi8Jl2pMbajgPbzX6ZGs=
